services:
  web:
    image: node:22.16.0
    volumes:
      - ${PWD:-./}:/workdir/nestjs-starter-project
    working_dir: /workdir/nestjs-starter-project
    command: bash -c "yarn start"
    depends_on:
      - postgres
    networks:
      - resource-network
    environment:
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=test
      - DB_NAME=product
      - DB_PORT=5432
      - PORT=8080
      - VERSION=${VERSION}
      - MIGRATION_AUTO=true
      - JWT_SECRET=mysupersecret
      - JWT_REFRESH_SECRET=myrefreshsecret 
    ports:
      - "8080:8080"
  postgres:
    image: postgres:17.5-alpine3.22
    networks:
      - resource-network
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product
    volumes:
      - my-db:/var/lib/postgresql/data
networks:
  resource-network:
    driver: bridge
volumes:
  my-db:
